cra-config.yaml

Update cra-config.yaml to use SCC from GoldenEye FSCloud Testing account

---

.github/settings.yml
README.md
tests/go.mod

rename repo to terraform-ibm-account-infrastructure-base

---

ibm_catalog.json

In 1.4.0 the profile name was renamed from "IBM Cloud for Financial Services" -> "IBM Cloud Framework for Financial Services"
```
/run pipeline
```

fix: claim controls from "IBM Cloud Framework for Financial Services" profile

---

.github/settings.yml

docs: add topics + description

---

.github/workflows/ci.yml
.github/workflows/release.yml
cra-config.yaml

add toolchain id to cra-config since this repo tests run in different account
```
/run pipeline
```

ci: add toolchain id to cra-config

---

cra-config.yaml
solutions/account-infrastructure-base/catalogValidationValues.json.template
solutions/account-infrastructure-base/main.tf
solutions/account-infrastructure-base/variables.tf
tests/pr_test.go

root level module already passes variable through to the iam account settings module, this change exposes that as a variable w/ default at the solution layer
also update common-dev-assets version which contains fixes for checkov on mac failing
resolves [terraform-ibm-account-infrastructure-base/issues#51](https://github.com/terraform-ibm-modules/terraform-ibm-account-infrastructure-base/issues/51)
expose var.allowed_ip_addresses in the solution
```
/run pipeline
```
- Use a conventional commit message to set the release level. …

feat: expose allowed_ip_addresses in the solution as a variable

---

README.md
examples/account-infrastructure-base

Add "Reference architectures" section to readme

---

ibm_catalog.json

Since we have no valid tags for category, we see this in catalog
```
/run pipeline
```

Update ibm_catalog.json with correct tags

---

cra-config.yaml
ibm_catalog.json

Update to fscloud 1.6.0

---

solutions/account-infrastructure-base/variables.tf

fix: get DA solution to execute if no allowlist is passed

---

.catalog-onboard-pipeline.yaml

Update .catalog-onboard-pipeline.yaml to mark ready: true

---

.secrets.baseline
README.md
main.tf
variables.tf

consume `skip_cloud_shell_calls` 
```
/run pipeline
```

feat: flag to toggle global shell settings

---

cra-config.yaml

Run tests and validation in GEDev account

---

ibm_catalog.json
solutions/account-infrastructure-base/variables.tf

docs: Update variables.tf and ibm_cloud_catalog.json - content edits 

---

solutions/account-infrastructure-base/catalogValidationValues.json.template
tests/pr_test.go

test: update tests to account for ipv6

---

ibm_catalog.json
solutions/account-infrastructure-base/variables.tf

Added description for prefix variable in ibm_catalog.json and modified description in variable.tf.
[#11959](https://github.ibm.com/GoldenEye/issues/issues/11959)
```
/run pipeline
```

Modified prefix description

---

ibm_catalog.json

Update variation name: `Resource group only` -> `Resource groups only`
https://github.ibm.com/GoldenEye/issues/issues/13210
```
/run pipeline
```

Update variation name: `Resource group only` -> `Resource groups only`

---

README.md
outputs.tf
solutions/fully-configurable/outputs.tf

Outputting `cbr_map_vpc_zoneid` to be consumed in SLZ to create CBR rule.
```
/run pipeline
```

fix: added output for cbr_map_vpc_zoneid

---

docs/about.md
docs/account-settings-configuration.md
docs/resource-group-configuration.md
ibm_catalog.json

docs: add comprehensive documentation for Cloud automation for Account Configuration

---

solutions/fully-configurable/variables.tf

fix: by default should create multiple groups

---

README.md
solutions/fully-configurable/version.tf
version.tf

Pull in the fix for https://github.com/IBM-Cloud/terraform-provider-ibm/issues/6269
```
/run pipeline
```

fix(deps): bump to ibm provider 1.79.0

---

README.md

Removed section containing broken link to reference architecture from README
https://github.ibm.com/GoldenEye/issues/issues/15302
```
/run pipeline
```

docs: removed broken link to ref architecture

---

ibm_catalog.json
solutions/fully-configurable/variables.tf

Adding UI regex validation.
Git_issue : https://github.ibm.com/GoldenEye/issues/issues/16144
Adding regex validation in ibm_catalog.json
```
/run pipeline
```

feat: add UI regex validation
